{% set name = "gglasso" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 104acc70d6de5341f8d2156b2cbc16cca54bb3dcec18b0ec6780a87c2684d9f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools

  run:
    - python >=3.7
    - numpy >=1.17.3
    - scipy >=0.11.0
    - scikit-learn >=0.24.1
    - numba >=0.46.0
    - pandas
    - matplotlib-base
    - seaborn
    - networkx
    - regain

test:
  imports:
    - gglasso
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/fabian-sp/GGLasso
  summary: "Algorithms for Single and Multiple Graphical Lasso problems."
  description: |
    This package contains algorithms for solving General Graphical Lasso (GGLasso) problems, 
    including single, multiple, as well as latent Graphical Lasso problems.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gglasso.readthedocs.io/en/latest/
  dev_url: https://github.com/fabian-sp/GGLasso

extra:
  recipe-maintainers:
    - Vlasovets
