{% set name = "gglasso" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b1a65175e8430babb61f24d3fd58ff87f97920ef1093655a91c3bc67976d557

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling

  run:
    - python >={{ python_min }}
    - numpy >=1.17.3
    - scipy >=0.11.0
    - scikit-learn >=0.24.1
    - numba >=0.46.0
    - pandas
    - matplotlib-base
    - seaborn
    - networkx

test:
  imports:
    - gglasso
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/fabian-sp/GGLasso
  summary: "Algorithms for Single and Multiple Graphical Lasso problems."
  description: |
    This package contains algorithms for solving General Graphical Lasso (GGLasso) problems, 
    including single, multiple, as well as latent Graphical Lasso problems.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://gglasso.readthedocs.io/en/latest/
  dev_url: https://github.com/fabian-sp/GGLasso

extra:
  recipe-maintainers:
    - Vlasovets
